<?php
/*
Plugin Name: Page Template Plugin : 'Good To Be Bad'
Plugin URI: http://hbt.io/
Version: 1.0.1
Author: Harri Bell-Thomas
Author URI: http://hbt.io/
*/

class PageTemplater {
        /**
         * A reference to an instance of this class.
         */
        private static $instance;
        /**
         * The array of templates that this plugin tracks.
         */
        protected $templates;
        /**
         * Returns an instance of this class. 
         */
        public static function get_instance() {
                if( null == self::$instance ) {
                    self::$instance = new PageTemplater();
                } 
                return self::$instance;
        } 
        /**
         * Initializes the template by setting filters and administration functions.
         */
        private function __construct() {
                $this->templates = array();
                // Add a filter to the attributes metabox to inject template into the cache.
                add_filter(
					'page_attributes_dropdown_pages_args',
					 array( $this, 'register_project_templates' ) 
				);
                // Add a filter to the save post to inject out template into the page cache
                add_filter(
					'wp_insert_post_data', 
					array( $this, 'register_project_templates' ) 
				);
                // Add a filter to the template include to determine if the page has our 
				// template assigned and return it's path
                add_filter(
					'template_include', 
					array( $this, 'view_project_template') 
				);
                // Add your templates to this array.
                $this->templates = array(
                        'gg-template.php'     => 'GG test template',
                );
				
        } 
        /**
         * Adds template to the pages cache in order to trick WordPress
         * into thinking the template file exists where it doens't really exist.
         *
         */
        public function register_project_templates( $atts ) {
                // Create the key used for the themes cache
                $cache_key = 'page_templates-' . md5( get_theme_root() . '/' . get_stylesheet() );
                // Retrieve the cache list. 
				// If it doesn't exist, or it's empty prepare an array
				$templates = wp_get_theme()->get_page_templates();
                if ( empty( $templates ) ) {
                        $templates = array();
                } 
                // New cache, therefore remove the old one
                wp_cache_delete( $cache_key , 'themes');
                // Now add our template to the list of templates by merging our templates
                // with the existing templates array from the cache.
                $templates = array_merge( $templates, $this->templates );
                // Add the modified cache to allow WordPress to pick it up for listing
                // available templates
                wp_cache_add( $cache_key, $templates, 'themes', 1800 );
                return $atts;
        } 
        /**
         * Checks if the template is assigned to a page
         */
        public function view_project_template( $template ) {
                global $post;
                if (!isset($this->templates[get_post_meta( 
					$post->ID, '_wp_page_template', true )] ) ) {
                        return $template;
                } 
                $file = plugin_dir_path(__FILE__). get_post_meta( 
					$post->ID, '_wp_page_template', true 
				);
				
                // Just to be safe, check if the file exist first
                if( file_exists( $file ) ) {
                        return $file;
                } 
				else { echo $file; }
                return $template;
        } 
} 
add_action( 'plugins_loaded', array( 'PageTemplater', 'get_instance' ) );


function template_test_activate() {

    // do this when plugin is activated 


    /******************
    * create custom page  
    *******************/
    $gg_custom_page = array(
        'post_title' => 'Grammar Guru TEST PAGE',
        'post_content' => 'This page was auto-generated by the Grammar Guru plugin. <br> >>> DO NOT EDIT OR DELETE THIS PAGE <<<',
        'post_status' => 'publish',
        'post_type' => 'page',
    );
    $temp_postID = wp_insert_post($temp_custom_page);
    update_post_meta( $temp_postID, '_wp_page_template', 'temp-template.php' );
    update_option( 'temp_page', $temp_custom_page_ID );
}
register_activation_hook( __FILE__, 'template_test_activate' );



/******************
* Deactivation Function 
*******************/
function temp_deactivate(){
    $id_to_delete = get_option( 'temp_page' );

    if( $id_to_delete ){
        wp_delete_post( $id_to_delete, true );
    }
}
register_deactivation_hook( __FILE__, 'temp_deactivate' ); 


?>
