<?php
/*
Plugin Name: Grammar Guru
Plugin URI: http://
Description: Grammar Guru helps students practice basic grammar in context
Author: Lisa Cavern
Version: 1.0
*/

/******************
* global variables
*******************/

$gg_plugin_name = 'Grammar Guru';

// declares settings and allows it to be retreived by the plugin
$gg_options = get_option('gg_settings');


/******************
* includes
*******************/

define( 'GG_PLUGIN_PATH', plugin_dir_path( __FILE__ ) );

/* see PD101 video 10 after 10:00 for more info and instructions */

if( is_admin() ) {
	include( GG_PLUGIN_PATH . 'includes/admin-page.php'); // admin page

}
else {
	include( GG_PLUGIN_PATH . 'includes/scripts.php'); // this controls all JS / CSS 
}

// include files needed by template 
include('includes/data-processing.php'); // this controls all saving of data
include('includes/display-functions.php');  // content display functions
include('includes/template-creator.php'); 


/******************
* Activation Function 
*******************/

$gg_db_version = '1.0';

function gg_activate() {

    /******************
    * create custom page  
    *******************/
    $gg_custom_page = array(
    	'post_title' => 'Grammar Guru',
    	'post_content' => 'This page was auto-generated by the Grammar Guru plugin. <br> >>> DO NOT EDIT OR DELETE THIS PAGE <<<',
    	'comment_status' => 'closed',
    	'post_status' => 'publish',
    	'post_type' => 'page',
    	);
    // create page
    $gg_custom_page_ID = wp_insert_post($gg_custom_page);
    // assign template 
    update_post_meta( $gg_custom_page_ID, '_wp_page_template', 'gg-template.php' );
    // save page id into options
    update_option( 'ggpage', $gg_custom_page_ID );

	/******************
	* database set up 
	*******************/

	global $wpdb;
	global $gg_db_version;
	$table_name = $wpdb->prefix . 'gg_tagged';
	$charset_collate = $wpdb->get_charset_collate();

	$sql = "CREATE TABLE $table_name (
		id mediumint(9) NOT NULL AUTO_INCREMENT,
		post_ID mediumint(9) NOT NULL,
		time datetime DEFAULT '0000-00-00 00:00:00' NOT NULL,
		post_title VARCHAR(100) NOT NULL,
		post_content TEXT NOT NULL,
		tagged_content TEXT NOT NULL,

		UNIQUE KEY id (id)
		) $charset_collate;";

require_once( ABSPATH . 'wp-admin/includes/upgrade.php' );
dbDelta( $sql );

update_option( 'gg_db_version', $gg_db_version );
}

register_activation_hook( __FILE__, 'gg_activate' );

/******************
* Deactivation Function 
*******************/
function gg_deactivate(){
	$id_to_delete = get_option( 'ggpage' );

	if( $id_to_delete ){
		wp_delete_post( $id_to_delete, true );
	}
}
register_deactivation_hook( __FILE__, 'gg_deactivate' ); 

/******************
* test area
*******************/

class GG_test {
	function __construct() {
		// $this->load();
	}
	function load() {
		add_action( 'admin_notices', array( $this, 'notice' ) );
	}
	function notice() {
		// echo '<div class="updated"><p>This is my admin notice. my plugin works!!</p></div>';
	}
}

$gg_test = new GG_test;

$gg_test->load();